[[session]]
name = "tmux conf"
path = "~/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "Sesh Config"
path = "~/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "ls ~/dotfiles/.config/sesh/"

[[session]]
name = "tmuxinator config"
path = "~/dotfiles/.config/tmuxinator/"
startup_command = "nvim ."

[[session]]
name = "fish config"
path = "~/dotfiles/fish/"
startup_command = "nvim ."


[[session]]
name = "nvim config"
path = "~/dotfiles/.config/kicknvim/"
startup_command = "nvim ."

